class Crypto {
    /*  
        @returns base64 encoded 256bit secret key 
    */
    static generateKey256(){
        return require('crypto').randomBytes(64).toString('base64').replaceAll('=','');
    }

    /*  
        @param target
            - data: json string
            - secretKey: generated by generateKey256()
    */
    static createHmacSha256(target){
        return require('crypto').createHmac('sha256', target.secretKey).update(JSON.stringify(target.data)).digest('hex');
    }
}

module.exports = {
    Crypto,
}